name: Portfolio Documentation Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Vérifier que le README existe et n'est pas vide
      - name: Validate README
        run: |
          if [ ! -f README.md ]; then
            echo "❌ README.md manquant"
            exit 1
          fi
          if [ ! -s README.md ]; then
            echo "❌ README.md est vide"
            exit 1
          fi
          echo "✅ README.md valide"

      # 3. Vérifier la structure du répertoire
      - name: Check repository structure
        run: |
          echo "📁 Structure du répertoire:"
          find . -type f -not -path "./.git/*" | sort
          echo "✅ Vérification de structure terminée"

      # 4. Validation finale
      - name: Final validation
        run: echo "✅ Validation terminée avec succès pour Yakoubi-Yamina-Portfolio-Global"
